### ISSUE TITLE
Некоторые замечания по коду

### ISSUE THREAD

**Issue by anst-foto** [vyshky/FileManager2#4]
[**Program.cs**](https://github.com/vyshky/FileManager2/blob/main/TcpServer/Program.cs)
- `static string path = "C:\\Users\\vyshk\\Desktop\\delete\\";` - абсолютный путь
- `static public void SetFileName(TcpClient newClient)` - перепутаны местами модификаторы
- ```csharp
     if (Encoding.Default.GetString(fileNameBuffer).Contains("<Name="))
            {
                //NetworkToHostOrder
                fileName = Encoding.Default.GetString(fileNameBuffer);
                fileName = fileName.Remove(fileName.IndexOf('\0'));
                fileName = fileName.Remove(0, fileName.IndexOf('=') + 1);
                fileName = fileName.Remove(fileName.IndexOf('>'));
                Console.WriteLine(fileName);
            }

Лучше использовать json или xml
- `static void ClientListener(object _newClient)` - почему бы не привести к нужному типу `_newClient`
- В функциях часть кода можно вынести в отдельные функции.
- нет логирования событий

---

[**MainWindow.xaml.cs**](https://github.com/vyshky/FileManager2/blob/main/FileManager2/MainWindow.xaml.cs)
- `string ip = "127.0.0.1";` - инициализация переменной вне конструктора
- отсутствие получения необходимых данных из конфигов
- `private void FORM_CLICK_BUTTON_CONNECTION` - правила именования для C# не выполняются. Плюс в разных местах одного файла по разному стили именования используются.
- `string name = $"<Name={path.Remove(0, i + 1)}>";` - странный формат данных

---

[**MainWindow.xaml**](https://github.com/vyshky/FileManager2/blob/main/FileManager2/MainWindow.xaml)
- `<TextBox x:Name="FORM_IP" Text="127.0.0.1" Margin="5" HorizontalContentAlignment="Center"/>` - не вынесены стили в отдельный файл
- `<StackPanel>` - не прописаны `Grid.Row` и `Grid.Column`

**Comment by iRussianHero** [comment]
> * `static void ClientListener(object _newClient)` - почему бы не привести к нужному типу `_newClient`

Не совсем понятно, что нужно сделать. У нас уже "_newClient" приведён к типу TcpClient.
P.S.: static void ClientListener(object _client) может принимать только "Object", т.к. запускаем в потоке.

**Comment by anst-foto** [comment]
> > * `static void ClientListener(object _newClient)` - почему бы не привести к нужному типу `_newClient`
> 
> Не совсем понятно, что нужно сделать. У нас уже "_newClient" приведён к типу TcpClient. P.S.: static void ClientListener(object _client) может принимать только "Object", т.к. запускаем в потоке.

А через лямбду не пробовали запускать без преобразований к `Object` и обратно
